pepiline{
    agent any {

        stages{
            stage('init'){
                steps{
                    sh 'terraform init -reconfigure -no-color'
                }
            }
            stage('validate'){
                steps{
                    sh 'terraform validate -no-color'
                }
            }
            stage('format'){
                steps{
                    sh 'fmt -no-color'
                }
            }
            stage('plan'){
                steps{
                    sh 'plan -no-color'
                }
            }
        }
    }
}